
SELECT * FROM CONTRALOR.TBCERTIFICADO WHERE NUMEROFORMULARIO IN (84753921 ,84174005 )

SELECT IDCERTIFICADO,IDLOTE,NUMEROGUIA,FECHAGUIA,NUMEROFORMULARIO,NUMEROPOLIZA,DESCRIPCION
FROM CONTRALOR.TBCERTIFICADO CER INNER JOIN CONTRALOR.TBESTADODOC EST ON CER.ESTADO = EST.IDESTADO    
WHERE NUMEROFORMULARIO IN (84753921 ,84174005 )

SELECT NUMEROFORMULARIO,NUMEROPOLIZA,ESTADO FROM CONTRALOR.TBCERTIFICADO WHERE NUMEROFORMULARIO IN (84753921 ,84174005 )

SELECT * FROM CONTRALOR.TBESTADOCERTIFICADO

UPDATE CONTRALOR.TBCERTIFICADO SET NUMEROFORMULARIO = 84754569 WHERE IDCERTIFICADO  =  11310371;

UPDATE CONTRALOR.TBCERTIFICADO SET NUMEROFORMULARIO = 84173069 WHERE IDCERTIFICADO  =  11273871;

UPDATE CONTRALOR.TBCERTIFICADO SET ESTADO = 'D' WHERE NUMEROFORMULARIO = 84125673;

UPDATE CONTRALOR.TBDISTRIBUCION_CERTIFICADO SET ESTADODIST = 'R' 
WHERE IDCERTIFICADO IN (SELECT IDCERTIFICADO FROM CONTRALOR.TBCERTIFICADO WHERE NUMEROFORMULARIO = 84125673)
AND IDDISTRIBUCION = (SELECT MAX(IDDISTRIBUCION) FROM CONTRALOR.TBDISTRIBUCION_CERTIFICADO WHERE IDCERTIFICADO IN (SELECT IDCERTIFICADO FROM CONTRALOR.TBCERTIFICADO WHERE NUMEROFORMULARIO = 84125673));

