PI_PAPEL := 'LA';
PI_GRUPO := 410;


PI_PAPEL := 'DI';
PI_GRUPO := 470;
      
SELECT * FROM CONTRALOR.TBINTERMEDIARIO WHERE IDINTERMEDIARIO = 12849      

SELECT TBR.IDOFICINA,TBC.IDCERTIFICADO, CASE
     WHEN TBC.NUMEROFORMULARIO IS NULL THEN TBC.NUMEROPOLIZA
         ELSE TBC.NUMEROFORMULARIO
      END NUM_FORM, TBP.TIPO_CERT, TBP.GRPO_VNTA, TBD.IDDISTRIBUCION, TRUNC (TBD.FECHADISTRIBUCION) AS FECHADISTRIBUCION,
      TBC.IDPRODUCTO, TBC.ESTADO, TBD.INTERMDESTINO
 FROM (SELECT T0.DESCRIPCION TIPO_CERT, T0.GRPO_VNTA, T0.IDPRODUCTO, T0.IDGRUPO, T0.FECHAINICIOCAMPANA, T0.FECHAFINCAMPANA
         FROM CONTRALOR.TBPRODUCTO T0
        WHERE T0.IDGRUPO = 410 AND T0.GRPO_VNTA = 'LA') TBP
      INNER JOIN
      CONTRALOR.TBCERTIFICADO TBC ON TBP.IDPRODUCTO = TBC.IDPRODUCTO
      INNER JOIN CONTRALOR.TBDISTRIBUCION_CERTIFICADO TDC ON TBC.IDCERTIFICADO = TDC.IDCERTIFICADO
      INNER JOIN CONTRALOR.TBDISTRIBUCION TBD ON TDC.IDDISTRIBUCION = TBD.IDDISTRIBUCION
      INNER JOIN CONTRALOR.TBREQUERIMIENTO TBR ON TBD.IDREQUERIMIENTO = TBR.IDREQUERIMIENTO
WHERE  1 = 1
   --AND TBC.NUMEROFORMULARIO = 84315966             
   AND TBC.ESTADO = 'D'
   AND TDC.ESTADODIST = 'R'
   AND TDC.RECIBIDO = 1
   AND TBD.INTERMDESTINO = 12849
   --AND TBR.IDOFICINA = 36                
                  
                  AND TBR.IDOFICINA = PI_IDOFICINA;      
                  
                  
select * from contralor.tbtipointermediario

select * from contralor.tbintermediario   where idintermediario =  10784

 -- 12571

select * from contralor.tbintermediario   where IDTIPOINTERM =  9 AND INTERMEDIARIOPADRE in (select IDINTERMEDIARIO from contralor.tbintermediario   where IDTIPOINTERM = 8)     

select * from contralor.tbintermediario   where IDTIPOINTERM =  8 AND INTERMEDIARIOPADRE in (select IDINTERMEDIARIO from contralor.tbintermediario   where IDTIPOINTERM = 8)                   

