DECLARE 
  PE_IN_RAMO VARCHAR2(20);
  PE_IN_ANIOINI NUMBER;
  PE_IN_ANIOANT NUMBER;
  PE_NU_TMONEDA NUMBER;
  PE_NU_IDUSO VARCHAR2(15);
  PE_VC_CLASE VARCHAR2(15);
  PE_VC_UBIGEO CHAR(6);
  PE_VC_IDMARCA VARCHAR2(15);
  PE_VC_IDMODEL VARCHAR2(15);
  PE_VC_TTIMON VARCHAR2(15);
  PE_CH_COBERTURA NUMBER;
  PE_CH_TIPOPERSONA CHAR(3);
  PE_NU_ASIENTOS VARCHAR2(15);
  PE_VC_SCLIENT VARCHAR2(15);
  PE_VC_SINTERMED VARCHAR2(15);
  PE_VC_SPOLICY VARCHAR2(15);
  PE_VC_PLACA VARCHAR2(200);
  PE_VC_STARTDATE DATE;
  PE_CH_MODALIDAD CHAR(1);
  PE_IN_IDAPP NUMBER;
  PE_VC_SROL VARCHAR2(15);
  PE_VC_IDDANIOPROPIO VARCHAR2(200);
  RC1 SYS_REFCURSOR;

BEGIN 
  PE_IN_RAMO := '66';
  PE_IN_ANIOINI := 2017;
  PE_IN_ANIOANT := 2017;
  PE_NU_TMONEDA := 1;
  PE_NU_IDUSO := '1';
  PE_VC_CLASE := '1';
  PE_VC_UBIGEO := '150101';
  PE_VC_IDMARCA := '6036';
  PE_VC_IDMODEL := '10001563';
  PE_VC_TTIMON := NULL;
  PE_CH_COBERTURA := NULL;
  PE_CH_TIPOPERSONA := NULL;
  PE_NU_ASIENTOS := NULL;
  PE_VC_SCLIENT := NULL;
  PE_VC_SINTERMED := '00000071483758';
  PE_VC_SPOLICY := NULL;
  PE_VC_PLACA := NULL;
  PE_VC_STARTDATE := SYSDATE;
  PE_CH_MODALIDAD := 'T';
  PE_IN_IDAPP := NULL;
  PE_VC_SROL := '00000000125574';
  PE_VC_IDDANIOPROPIO := 'N';
  -- RC1 := NULL;  Modify the code to initialize this parameter

  BDTARVEH.SP_TTARIFAMOD_GET ( PE_IN_RAMO, PE_IN_ANIOINI, PE_IN_ANIOANT, PE_NU_TMONEDA, PE_NU_IDUSO, PE_VC_CLASE, PE_VC_UBIGEO, PE_VC_IDMARCA, PE_VC_IDMODEL, 
  PE_VC_TTIMON, PE_CH_COBERTURA, PE_CH_TIPOPERSONA, PE_NU_ASIENTOS, PE_VC_SCLIENT, PE_VC_SINTERMED, PE_VC_SPOLICY, PE_VC_PLACA, PE_VC_STARTDATE, PE_CH_MODALIDAD, 
  PE_IN_IDAPP, PE_VC_SROL, PE_VC_IDDANIOPROPIO, :RC1 );
  COMMIT; 
END; 