
select NBRANCH,NPOLICY,SPOLITYPE, SCOLINVOT from insudb.policy where npolicy in (select DISTINCT NUMBER1 from TMPINFORMAC 
)
order by branch

select * from TMPINFORMAC WHERE NUMBER1= 0 



CREATE SYNONYM LUIMICH1.TMPINFORMAC FOR INSUDB.TMPINFORMAC;

GRANT ALL ON INSUDB.TMPINFORMAC TO LUIMICH1;