--PKG_BRANDMODEL

SELECT NVEHBRAND,SDESCRIPT
  FROM TAB_AU_BRA
 WHERE DEFFECDATE <= SYSDATE
   AND (   DNULLDATE IS NULL
        OR DNULLDATE > SYSDATE)
        AND SSTATREGT = 1
        
--ORDER BY SDESCRIPT        

SELECT * FROM (
SELECT  INSUDB.GETBRAND(VER.SVERSION,VER.DEFFECDATE,2,'1',0,0) AS CodigoMarca,
INSUDB.GETBRAND(VER.SVERSION,VER.DEFFECDATE,1,'1',0,0) AS Marca,
VER.SVERSION AS CodigoModelo, 
INSUDB.GETMODEL(VER.SVERSION,VER.DEFFECDATE,1,'1',0,0)  AS MODELO,
VER.SDESVERSION AS SVERSION,
CLA.NVEHTYPE IDCLASE,
CLA.SDESCRIPT CLASE
FROM INSUDB.TAB_AU_VER VER INNER JOIN  table226 CLA ON CLA.NVEHTYPE = VER.NVEHTYPE
WHERE VER.SSTATREGT = '1' 
AND VER.DNULLDATE IS NULL
) ORDER BY MARCA,MODELO,SVERSION,CLASE 


SELECT * FROM 
(
SELECT TV.NVEHTYPE CODIGOCLASE, 
       UPPER (REAGENERALPKG.REACODIGINT ('TABLE226','NVEHTYPE',TV.NVEHTYPE)) DESCRIPTCLASE, 
       TB.NVEHBRAND CODIGOMARCA,TB.SDESCRIPT DESCRIPTMARCA,
       TM.SVEHCODE CODIGOMODELO,TM.SVEHMODEL DESCRIPTMODELO,       
       TV.SVERSION CODIGOVERSION,UPPER (TV.SDESVERSION) DESCRIPTVERSION, 
       TV.NVEHPLACE ASIENTOS, 
       TV.SGENERIC CODGENERICO, DECODE (SGENERIC,1,'GENÉRICA','ESPECÍFICA') DESCRIPTGENERIC
  FROM INSUDB.TAB_AU_VER TV, INSUDB.TAB_AU_MOD TM, INSUDB.TAB_AU_BRA TB
 WHERE TV.NVEHBRAND = TB.NVEHBRAND
   AND TV.SVEHCODE = TM.SVEHCODE
   AND TM.NVEHBRAND = TB.NVEHBRAND
   AND TV.DEFFECDATE <= SYSDATE
   AND (   TV.DNULLDATE IS NULL
        OR TV.DNULLDATE > SYSDATE)
   AND TM.DEFFECDATE <= SYSDATE
   AND (   TM.DNULLDATE IS NULL
        OR TM.DNULLDATE > SYSDATE)
   AND TB.DEFFECDATE <= SYSDATE
   AND (   TB.DNULLDATE IS NULL
        OR TB.DNULLDATE > SYSDATE)  
)        
ORDER BY DESCRIPTCLASE,DESCRIPTMARCA,DESCRIPTMODELO,DESCRIPTVERSION    


