 
insert into ADMINISTRADOR_INTERMEDIARIO 
(id_usu,intermed, fec_crea)
select 24370,intermed,GETDATE() from USUARIO where login in ('cmactacna01',
'admcmactgrer0',
'admcmactpt0',
'admcmactcorm0',
'admcmactpun0',
'admcmactilo0',
'admcmactmoqu0',
'admcmactleon0',
'admcmactsanmar0',
'admcmactalto0',
'admcmactmazu0',
'admcmactjuli0',
'admcmacthigue0',
'admcmactciudad0',
'admcmactarq0',
'admcmactpno0',
'admcmactsj0',
'admcmacthue0',
'admcmactibe0',
'admcmactbyr0',
'admcmactlav0',
'admcmaccusc0',
'admcmacilav0',
'admcmacdsgro0',
'admcmaccaym0',
'admcmacmvalle0',
'admcmacnegrit0',
'admcmactica0',
'admcmactpdrg0',
'admcmactcrroc0')