--TRUNCATE TABLE [LPGSLBDPRD01].BRANDMODEL.dbo.TAB_AU_BRA
/*
TRUNCATE TABLE BRANDMODEL.dbo.TAB_AU_BRA
TRUNCATE TABLE BRANDMODEL.dbo.TAB_AU_MOD
TRUNCATE TABLE BRANDMODEL.dbo.TAB_AU_VER
TRUNCATE TABLE BRANDMODEL.dbo.TAB_EQUI_VEH
TRUNCATE TABLE BRANDMODEL.dbo.tblTabla226
*/
--SELECT * FROM [LPGSLBDPRD01].[BRANDMODEL].[dbo].[TAB_AU_BRA] -- 14 seg.
INSERT INTO [LPGSLBDPRD01].BRANDMODEL.dbo.TAB_AU_BRA ([NVEHBRAND],[SDESCRIPT],[NORIGIN],[DEFFECDATE],[DNULLDATE],[SSTATREGT],[DCOMPDATE],[NUSERCODE],[NPERCENT_VC])
SELECT [NVEHBRAND],[SDESCRIPT],[NORIGIN],[DEFFECDATE],[DNULLDATE],[SSTATREGT],[DCOMPDATE],[NUSERCODE],[NPERCENT_VC]
FROM BRANDMODEL.dbo.TAB_AU_BRA NTBRA 

--SELECT * FROM [LPGSLBDPRD01].[BRANDMODEL].[dbo].[TAB_AU_MOD] -- 14 seg.
INSERT INTO [LPGSLBDPRD01].[BRANDMODEL].[dbo].[TAB_AU_MOD] ([SVEHCODE],[NVEHBRAND],[SVEHMODEL],[SDESCRIPT],[NVEHTYPE],[DEFFECDATE],[DNULLDATE],[SSTATREGT],[DCOMPDATE],[NUSERCODE])
SELECT [SVEHCODE],[NVEHBRAND],[SVEHMODEL],[SDESCRIPT],[NVEHTYPE],[DEFFECDATE],[DNULLDATE],[SSTATREGT],[DCOMPDATE],[NUSERCODE]
FROM BRANDMODEL.dbo.TAB_AU_MOD where dnulldate is null
--14 seg.

--SELECT * FROM [LPGSLBDPRD01].[BRANDMODEL].[dbo].[TAB_AU_VER]  -- 15 seg.
INSERT INTO [LPGSLBDPRD01].[BRANDMODEL].[dbo].[TAB_AU_VER] ([SVERSION],[NVEHBRAND],[SVEHCODE],[SDESVERSION],[SDESCRIPT],[NVEHPLACE],[NVEHTYPE],[SGENERIC],[NVEHPMA],[DEFFECDATE],[DNULLDATE],[SSTATREGT],[DCOMPDATE],[NUSERCODE])
SELECT [SVERSION],[NVEHBRAND],[SVEHCODE],[SDESVERSION],[SDESCRIPT],[NVEHPLACE],[NVEHTYPE],[SGENERIC],[NVEHPMA],[DEFFECDATE],[DNULLDATE],[SSTATREGT],[DCOMPDATE],[NUSERCODE]
FROM BRANDMODEL.dbo.TAB_AU_VER WITH (NOLOCK)

--SELECT * FROM [LPGSLBDPRD01].[BRANDMODEL].[dbo].[TAB_EQUI_VEH]  -- 15 seg.
INSERT INTO [LPGSLBDPRD01].[BRANDMODEL].[dbo].[TAB_EQUI_VEH]([ID_EQUI_VEH],[NVEHBRANDVT_ORI],[SVEHCODEVT_ORI],[SVEHCODEINX_ORI],[NVEHBRAND],[SVEHCODE],[SVERSION],[DEFFECDATE],[DNULLDATE],[SSTATREGT],[DCOMPDATE],[NUSERCODE])
SELECT [ID_EQUI_VEH],[NVEHBRANDVT_ORI],[SVEHCODEVT_ORI],[SVEHCODEINX_ORI],[NVEHBRAND],[SVEHCODE],[SVERSION],[DEFFECDATE],[DNULLDATE],[SSTATREGT],[DCOMPDATE],[NUSERCODE]
FROM BRANDMODEL.dbo.TAB_EQUI_VEH   WITH (NOLOCK)

--SELECT * FROM [LPGSLBDPRD01].[BRANDMODEL].[dbo].[tblTabla226]  -- 0 seg.
INSERT INTO [LPGSLBDPRD01].[BRANDMODEL].[dbo].[tblTabla226]  ([SDESCRIPT],[SSHORT_DES],[NVEHTYPE],[SSTATREGT],[DCOMPDATE],[NUSERCODE])
SELECT [SDESCRIPT],[SSHORT_DES],[NVEHTYPE],[SSTATREGT],[DCOMPDATE],[NUSERCODE]
FROM BRANDMODEL.dbo.tblTabla226  WITH (NOLOCK)    

 /*

SELECT [SVERSION],[NVEHBRAND],[SVEHCODE],[SDESVERSION],[SDESCRIPT],[NVEHPLACE],[NVEHTYPE],[SGENERIC],[NVEHPMA],[DEFFECDATE],[DNULLDATE],[SSTATREGT],[DCOMPDATE],[NUSERCODE]
FROM BRANDMODEL.dbo.TAB_AU_VER WITH (NOLOCK) --where sdescript like '%YUEJIN/NJ1028%'
order by nvehtype,sdescript

 
 SELECT [NVEHBRAND],[SDESCRIPT],[NORIGIN],[DEFFECDATE],[DNULLDATE],[SSTATREGT],[DCOMPDATE],[NUSERCODE],[NPERCENT_VC]
FROM BRANDMODEL.dbo.TAB_AU_BRA NTBRA  where sdescript like '%YUEJIN%' and  deffecdate = '1900-01-01 00:00:00.000'

SELECT * FROM BRANDMODEL.dbo.TAB_AU_BRA WHERE NVEHBRAND= 6509

--delete FROM BRANDMODEL.dbo.TAB_AU_BRA  where [NVEHBRAND] =6509  and  deffecdate = '2015-09-05 00:00:00.000'

SELECT [NVEHBRAND], COUNT(*)
FROM BRANDMODEL.dbo.TAB_AU_BRA NTBRA  
WHERE DNULLDATE IS NULL
GROUP BY  [NVEHBRAND]
HAVING COUNT(*)>1

SELECT SVEHCODE, COUNT(*)
FROM BRANDMODEL.dbo.TAB_AU_MOD
WHERE DNULLDATE IS NULL
GROUP BY [SVEHCODE]
HAVING COUNT(*)>1


SELECT SVERSION,  COUNT(*)
FROM BRANDMODEL.dbo.TAB_AU_VER
WHERE DNULLDATE IS NULL
GROUP BY [SVERSION]
HAVING COUNT(*)>1

SELECT * FROM BRANDMODEL.dbo.TAB_AU_VER 



*/

 

 select * from USuario